"""Initial migration.

Revision ID: 22e6dcfb830c
Revises: 
Create Date: 2022-12-29 00:37:36.260990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e6dcfb830c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usn', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friends', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('usn')

    # ### end Alembic commands ###
